exposed timeout from the C++ tryRecv function in the try_recv/_raw python class
vitillo/python-yampl pull request #3
Opened 2017-12-05 18:39 UTC by jtchilders

Hi, I think I managed to do this properly. Could you please make it permanent?
Thanks.

2017-12-05 22:14 UTC, vitillo requested changes
Thanks for contributing back! :)

2017-12-05 22:14 UTC, vitillo commented on yampl.pyx
> +		ssize_t tryRecv(void *&buffer,long timeout) except +
nit: please add a space after the comma, the same applies to your other changes

2017-12-05 22:14 UTC, vitillo commented on yampl.pyx
> +		ssize_t tryRecv(void *&buffer,long timeout) except +
This isn't backwards compatible. Please ensure that the public API isn't changed; you could for example use a default value for the `timeout` parameter.

2017-12-06 14:45 UTC, jtchilders commented
OK, I think I've addressed your comments. Have a look again.

2017-12-12 15:49 UTC, jtchilders commented
Hi can you integrate these changes or am I still missing something?

2017-12-12 20:24 UTC, vitillo requested changes

2017-12-12 20:24 UTC, vitillo commented on yampl.pyx
> +	def try_recv(self,timeout=0):
nit: please use proper formatting (space after comma)

2017-12-12 20:24 UTC, vitillo commented on yampl.pyx
> +	def try_recv(self,timeout=0):
The same applies to your other changes

2017-12-12 20:24 UTC, vitillo commented
I must have missed Github's notification of your changes, sorry about that.

2017-12-12 21:09 UTC, jtchilders commented
Done.

2017-12-12 21:23 UTC, vitillo commented
LGTM, thanks!

2017-12-12 21:23 UTC, merged